# -----------------------------------------------------------------------
# Tasks for linux systems
# -----------------------------------------------------------------------
- name: Include Linux tasks
  include_tasks: linux.yml
  when: ansible_os_family != 'Windows'

# -----------------------------------------------------------------------
# Tasks for Windows
# -----------------------------------------------------------------------
- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
