---
- hosts: all

  roles:
    - role: base_boost
      collections_enabled: true
      compile_boost: true
      clean_boost: false  # for idempotency
      compile_boost_with:
        --with-iostreams
