---
- name: Converge
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  vars:
    role_name: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') | basename }}"
    collections_enabled: true
    compile_boost: true
    clean_boost: false  # for idempotency
    compile_boost_with:
      --with-iostreams
  tasks:
    - name: "Include {{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_name }}"
