---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later
platforms:
  #  - name: base-boost-ubi8
  #    image: registry.access.redhat.com/ubi8/ubi
  #    privileged: true
  - name: base-boost-centos8
    image: quay.io/centos/centos:stream8
    privileged: true
  - name: base-boost-centos7
    image: centos:7
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
