---
- hosts: all

  pre_tasks:
    - name: RedHat 8
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version|int > 7
      set_fact:
        collections_enabled: false
        development_groupinstall: false
        cplusplusrpms:
          - make
          - diffutils
          - which

    - name: RedHat 7
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version|int <= 7
      set_fact:
        collections_enabled: true
        development_groupinstall: false
        cplusplusrpms:
          - make
  roles:
    - role: dockpack.base_gcc
